config/routes.rb
Rails.application.routes.draw do
  devise_for :authors, controllers: { :omniauth_callbacks => "authors/omniauth_callbacks" }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  resources :posts
  resources :comments
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  belongs_to :author
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i(show edit update destroy)
  before_action :set_comment, only: %i(show)
  before_action :authenticate_author!

  def index
    @posts = Post.page(params[:page]).per(5)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(
      post_params
    )

    @post.save!
    redirect_to posts_path
  end

  def update
    @post.update!(post_params)

    redirect_to post_path(@post)
  end

  def destroy
    @post.comments.destroy_all
    @post.destroy

    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(
      :title, :body, :author_id
    )
  end

  def set_post
    @post = Post.includes(
      comments: :author
    ).find(params[:id])
  end

  def set_comment
    @comment = Comment.new
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h1>Edit Post: <%= @post.id %></h1>

<%= form_with model: @post do |form| %>
  <div>
    <%= form.hidden_field :author_id, :value => current_author.id %>
    
    <%= form.label :title %><br>
    <%= form.text_field :title %>

    <br><br>

    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<%= link_to "New Post", new_post_path %>

<ul>
  <% @posts.each do |post| %>
    <li><a href="/posts/<%= post.id %>"><%= post.title %></a></li>
  <% end %>
</ul>

<%= paginate @posts %>


<% if author_signed_in? %>
  <li> <%= link_to('Logout', destroy_author_session_path, :method => :delete) %> </li>
<% else %>
  <li> <%= link_to('Login', new_author_session_path) %> </li>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_with model: @post do |form| %>
  <div>
    <%= form.hidden_field :author_id, :value => current_author.id %>
    
    <%= form.label :title %><br>
    <%= form.text_field :title %>

    <br><br>

    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/show.html.erb
<%= link_to "Back", posts_path %>

<br />

<%= link_to "Edit Post", edit_post_path(@post) %>

<%= link_to "Delete Post", post_path(@post), method: :delete,
  data: { confirm: "Are you sure?" } %>

<h1>Title: <%= @post.title %></h1>

<p>Body: <%= @post.body %></p>

<span>Author: <%= @post.author.email %></p>

<h3>Comments</h3>

<ul>
  <% @post.comments.each do |comment| %>
    <li><%= comment.author.email %>: <%= comment.body %></li>
  <% end %>
</ul>


<h1>New Comment</h1>

<%= form_with model: @comment do |form| %>
  <div>
    <%= form.hidden_field :post_id, :value => @post.id %>
    <%= form.hidden_field :author_id, :value => current_author.id %>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>